<article class="legal-document">
<h1>Voicely Translate Terms of Service</h1>
<p><strong>Last Updated: August 9, 2026</strong></p>
<p>These Terms of Service (&quot;Terms&quot;) govern your use of the Voicely
Translate Discord bot (&quot;Voicely Translate,&quot; the &quot;Bot,&quot; or the
&quot;Service&quot;). By installing, accessing, purchasing credits for, or using
Voicely Translate, you agree to these Terms.</p>
<h2>1. The Service</h2>
<p>Voicely Translate is a Discord bot that can join voice channels,
transcribe speech, identify supported languages, translate transcribed
speech into selected languages, and post the resulting text in Discord.</p>
<p>The Service may also provide usage credits, trial access, configurable
server settings, and integrations used to process credit purchases.</p>
<p>Voicely Translate relies on third-party services, including Discord,
OpenAI, Ko-fi, and infrastructure providers. Availability or
functionality may therefore be affected by services outside our control.</p>
<h2>2. Eligibility and Authorization</h2>
<p>You must comply with Discord&#39;s Terms of Service and all laws and rules
applicable to your use of Voicely Translate.</p>
<p>You may only use the Bot in servers and voice channels where you are
authorized to do so. Server administrators are responsible for
determining whether use of voice transcription and translation is
appropriate for their server and for providing any notices or obtaining
any consent required by applicable law.</p>
<p>Do not use Voicely Translate to secretly record, monitor, transcribe, or
otherwise surveil people where doing so would violate applicable law or
the rights of another person.</p>
<h2>3. Transcription and Translation</h2>
<p>Voicely Translate uses automated systems to process speech and generate
transcriptions and translations.</p>
<p>Automated transcription, language identification, and translation can be
inaccurate. The Service may mishear speech, identify the wrong language,
omit words, misunderstand context, or produce an incorrect translation.</p>
<p>You should not rely on Voicely Translate for emergency communications,
legal advice, medical decisions, safety-critical information, or any
other situation where an inaccurate transcription or translation could
cause significant harm.</p>
<h2>4. Voice Data</h2>
<p>When the Bot is actively being used in a voice channel, audio may be
processed as necessary to provide transcription and translation.</p>
<p>The Service is not intended to function as a permanent voice-recording
or archival service. Additional information about how data is handled is
provided in the Voicely Translate Privacy Policy.</p>
<h2>5. Credits and Paid Usage</h2>
<p>Some use of Voicely Translate may require prepaid Voicely Credits.</p>
<p>Unless otherwise stated at the time of purchase:</p>
<ul>
<li>100 Voicely Credits represents $1.00 USD of purchased credit.</li>
<li>Credits are consumed according to the Service&#39;s usage-cost
calculation.</li>
<li>The amount of credit consumed can vary depending on transcription
and translation usage.</li>
<li>Credits are associated with the Discord server to which they are
activated, rather than with an individual Discord user.</li>
<li>Credits have no cash value and cannot be exchanged for cash.</li>
</ul>
<p>The Service may apply a usage-cost multiplier above the underlying cost
of third-party services. The amount charged in Voicely Credits therefore
does not necessarily equal the amount paid by the Service to a
third-party provider for a particular request.</p>
<p>Pricing, credit rates, and usage calculations may be changed for future
purchases or future usage. Material changes will not retroactively
reduce credits that have already been purchased and added to a server
solely because the purchase price later changes.</p>
<h2>6. Credit Activation</h2>
<p>Credit purchases may require a server-specific activation code, such as
a <code>VT-XXXXXX</code> code generated by the <code>/topup</code> command.</p>
<p>You are responsible for entering the correct activation code when
purchasing credits. Credits are assigned according to the activation
code supplied with the purchase.</p>
<p>If an activation code is missing or incorrect, automatic activation may
fail. Contact the Service operator if you believe a valid purchase was
not properly credited.</p>
<h2>7. Payments and Refunds</h2>
<p>Payments for Voicely Credits may be processed by Ko-fi or another
disclosed payment provider. Payment processing is also subject to the
payment provider&#39;s terms and policies.</p>
<p>Except where required by law or otherwise stated at the time of
purchase, used credits are non-refundable.</p>
<p>If you experience a duplicate charge, failed credit activation, or
another payment problem, contact the Service operator so the transaction
can be reviewed.</p>
<p>Chargebacks, payment reversals, fraud, or abuse may result in
corresponding credits being removed and access to paid features being
restricted.</p>
<h2>8. Trials and Promotional Credits</h2>
<p>Voicely Translate may provide free trials, complimentary credits,
promotional credits, or unrestricted access to selected servers.</p>
<p>Trial and promotional access may be limited, changed, or discontinued at
any time. Free or promotional credits have no cash value.</p>
<h2>9. Acceptable Use</h2>
<p>You may not use Voicely Translate to:</p>
<ul>
<li>Violate applicable law or another person&#39;s rights.</li>
<li>Harass, threaten, stalk, or unlawfully monitor another person.</li>
<li>Circumvent access restrictions, credit requirements, rate limits, or
security controls.</li>
<li>Exploit bugs or vulnerabilities to obtain unpaid service.</li>
<li>Interfere with the Bot, its infrastructure, or other users&#39; access
to the Service.</li>
<li>Use automated requests or other methods intended to create
unreasonable load or excessive costs.</li>
<li>Misrepresent generated translations or transcriptions as guaranteed
to be accurate.</li>
<li>Use the Service in a manner prohibited by the terms of an applicable
third-party provider.</li>
</ul>
<p>We may restrict or terminate access when reasonably necessary to prevent
abuse, fraud, security problems, excessive disruption, or violations of
these Terms.</p>
<h2>10. Availability and Changes</h2>
<p>Voicely Translate is provided on an as-available basis.</p>
<p>The Bot may be unavailable because of maintenance, software errors,
internet outages, Discord outages, third-party API outages, account
limitations, rate limits, or other circumstances.</p>
<p>Features may be added, modified, suspended, or removed. We do not
guarantee uninterrupted availability or that every feature will continue
to be offered indefinitely.</p>
<h2>11. Third-Party Services</h2>
<p>Voicely Translate may interact with third-party services such as
Discord, OpenAI, Ko-fi, and Cloudflare.</p>
<p>Your use of those services may also be governed by their own terms and
privacy policies. We are not responsible for outages, changes, or
actions of third-party services outside our reasonable control.</p>
<h2>12. Disclaimer of Warranties</h2>
<p>To the maximum extent permitted by law, Voicely Translate is provided
&quot;as is&quot; and &quot;as available,&quot; without warranties of any kind, express or
implied.</p>
<p>We do not warrant that the Service will be uninterrupted, error-free,
completely secure, or that any transcription, translation, language
identification, usage calculation, or other generated output will be
completely accurate.</p>
<h2>13. Limitation of Liability</h2>
<p>To the maximum extent permitted by applicable law, the operator of
Voicely Translate will not be liable for indirect, incidental, special,
consequential, exemplary, or punitive damages arising from or related to
use of the Service.</p>
<p>Where liability cannot legally be excluded, liability will be limited to
the maximum extent permitted by applicable law.</p>
<p>Nothing in these Terms excludes rights or remedies that cannot lawfully
be excluded.</p>
<h2>14. Termination</h2>
<p>You may stop using Voicely Translate at any time and may remove the Bot
from your Discord server.</p>
<p>We may suspend or terminate access to the Service when reasonably
necessary for security, legal compliance, abuse prevention, nonpayment,
violation of these Terms, or discontinuation of the Service.</p>
<h2>15. Changes to These Terms</h2>
<p>These Terms may be updated as Voicely Translate changes. The &quot;Last
Updated&quot; date at the top of this document will be revised when the Terms
are updated.</p>
<p>Continued use of the Service after updated Terms take effect constitutes
acceptance of the updated Terms to the extent permitted by applicable
law.</p>
<h2>16. Contact</h2>
<p>Questions about these Terms, billing issues, or Voicely Translate should
be directed to Gozar Productions LLC through the official support server or our email:</p>
<p>Official support server: <a href="https://discord.gozarproductions.com">https://discord.gozarproductions.com</a></p>
<p>Email: <a href="mailto:contact@gozarproductions.com">contact@gozarproductions.com</a></p>
</article>
